# pyproject.toml


[tool.pyright]
extraPaths = [ 'src/python/main', 'src/python/test' ]
venvPath = '.'
venv = '.venv'


[tool.pytest]
cache_dir = '.pytest/cache'
pythonpath = [ 'src/python/main' ]
testpaths = [ 'src/python/test' ]


